# Uncomment the next line to define a global platform for your project
# platform :ios, ‘8.0’

target 'MMBaseMoudle' do
  pod 'AFNetworking', '~> 3.1.0'
pod 'RTRootNavigationController', '~> 0.5.23'
pod 'MMDrawerController', '~> 0.6.0'
pod 'SDWebImage', '~> 3.8.2'
pod 'MJExtension', '~> 3.0.13'
pod 'pop', '~> 1.0.10'
pod 'Masonry'
pod 'HMSegmentedControl', '~> 1.5.4'

pod 'ReactiveCocoa', '2.5'
pod 'MBProgressHUD', '~> 1.0.0'

pod 'UMengUShare/Social/WeChat'
pod 'UMengUShare/Social/QQ'
pod 'UMengUShare/Social/Sina'
pod 'Qiniu', '~> 7.1'
pod 'FMDB'
pod 'Reachability'

end
